version: "3.8"

services:
    app:
        container_name: laravel
        restart: unless-stopped
        build:
            args:
                user: laravel
                uid: '1000'
            context: ./docker/php-8.1
            dockerfile: Dockerfile
        tty: true
        volumes:
            - ./coding-challange-backend/:/usr/share/nginx/html
        depends_on:
            - db
        networks:
            - mynet
    db:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        restart: always
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - mynet
    web:
        container_name: nginx
        image: nginx:latest
        volumes:
            - ./coding-challange-backend/:/usr/share/nginx/html
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - app
        networks:
            - mynet
    html:
        container_name: frontend
        build:
            context: ./coding-challange-frontend
            dockerfile: Dockerfile
        volumes:
            - ./docker/nginx/spa.vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

volumes:
    dbdata:

networks:
    mynet:
        driver: bridge
